// <auto-generated />
using System;
using BusinessLogic.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Entities.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvertisementText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ThumbnailImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ThumbnailImageId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("AttributeId");

                    b.ToTable("AdvertisementAttributeValues");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementBookmark", b =>
                {
                    b.Property<int>("BookmarkOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("BookmarkedAdvertisementId")
                        .HasColumnType("integer");

                    b.HasKey("BookmarkOwnerId", "BookmarkedAdvertisementId");

                    b.HasIndex("BookmarkedAdvertisementId");

                    b.ToTable("AdvertisementBookmarks");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementNotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string[]>("Keywords")
                        .HasColumnType("text[]");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributeValueListId")
                        .HasColumnType("integer");

                    b.Property<int>("FilterType")
                        .HasColumnType("integer");

                    b.Property<int?>("IconId")
                        .HasColumnType("integer");

                    b.Property<bool>("Searchable")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sortable")
                        .HasColumnType("boolean");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.Property<string>("ValueValidationRegex")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeValueListId");

                    b.HasIndex("IconId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AttributeValueLists");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeValueListId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributeValueListId");

                    b.ToTable("AttributeValueListEntries");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvertisementCount")
                        .HasColumnType("integer");

                    b.Property<bool>("CanContainAdvertisements")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BusinessLogic.Entities.CategoryAttribute", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeOrder")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("CategoryAttributes");
                });

            modelBuilder.Entity("BusinessLogic.Entities.CategoryIdsResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("_", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvertisementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("BusinessLogic.Entities.ChatUser", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatUser");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasDiscriminator().HasValue("File");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BusinessLogic.Entities.LocaleText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LocaleTexts");

                    b.HasDiscriminator().HasValue("LocaleText");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<int>("FromUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMessageRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("FromUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BusinessLogic.Entities.NotificationSubscriptionAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("NotificationSubscriptionValues");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BusinessLogic.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("BusinessLogic.Entities.RuleViolationReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportedAdvertisementId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReporterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportedAdvertisementId");

                    b.HasIndex("ReporterId");

                    b.ToTable("RuleViolationReports");
                });

            modelBuilder.Entity("BusinessLogic.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneNumberPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkToUserSite")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProfileImageFileId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.Image", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.Files.File");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.MessageAttachment", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.Files.File");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.HasIndex("MessageId");

                    b.HasDiscriminator().HasValue("MessageAttachment");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeNameLocaleText", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.LocaleText");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.HasIndex("AttributeId");

                    b.HasDiscriminator().HasValue("AttributeNameLocaleText");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListEntryLocaleText", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.LocaleText");

                    b.Property<int>("AttributeValueListEntryId")
                        .HasColumnType("integer");

                    b.HasIndex("AttributeValueListEntryId");

                    b.HasDiscriminator().HasValue("AttributeValueListEntryLocaleText");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListLocaleText", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.LocaleText");

                    b.Property<int>("AttributeValueListId")
                        .HasColumnType("integer");

                    b.HasIndex("AttributeValueListId");

                    b.HasDiscriminator().HasValue("AttributeValueListLocaleText");
                });

            modelBuilder.Entity("BusinessLogic.Entities.CategoryNameLocaleText", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.LocaleText");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("CategoryNameLocaleText");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.AdvertisementImage", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.Files.Image");

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasIndex("AdvertisementId");

                    b.HasDiscriminator().HasValue("AdvertisementImage");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.SystemImage", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.Files.Image");

                    b.HasDiscriminator().HasValue("SystemImage");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.UserImage", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.Files.Image");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("UserImage");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Advertisement", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", "Owner")
                        .WithMany("OwnedAdvertisements")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Files.File", "ThumbnailImage")
                        .WithMany()
                        .HasForeignKey("ThumbnailImageId");

                    b.Navigation("Category");

                    b.Navigation("Owner");

                    b.Navigation("ThumbnailImage");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementAttributeValue", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Advertisement", "Advertisement")
                        .WithMany("AttributeValues")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementBookmark", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", "BookmarkOwner")
                        .WithMany("AdvertisementBookmarks")
                        .HasForeignKey("BookmarkOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Advertisement", "BookmarkedAdvertisement")
                        .WithMany("AdvertisementBookmarks")
                        .HasForeignKey("BookmarkedAdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookmarkOwner");

                    b.Navigation("BookmarkedAdvertisement");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementNotificationSubscription", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Attribute", b =>
                {
                    b.HasOne("BusinessLogic.Entities.AttributeValueList", "AttributeValueList")
                        .WithMany()
                        .HasForeignKey("AttributeValueListId");

                    b.HasOne("BusinessLogic.Entities.Files.SystemImage", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.Navigation("AttributeValueList");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListEntry", b =>
                {
                    b.HasOne("BusinessLogic.Entities.AttributeValueList", "AttributeValueList")
                        .WithMany("ListEntries")
                        .HasForeignKey("AttributeValueListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValueList");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Category", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BusinessLogic.Entities.CategoryAttribute", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Attribute", "Attribute")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Category", "Category")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Chat", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdvertisementId");

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("BusinessLogic.Entities.ChatUser", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Chat", "Chat")
                        .WithMany("ChatUsers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Message", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("BusinessLogic.Entities.NotificationSubscriptionAttributeValue", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.AdvertisementNotificationSubscription", "Subscription")
                        .WithMany("AttributeFilters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("BusinessLogic.Entities.RolePermission", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessLogic.Entities.RuleViolationReport", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Advertisement", "ReportedAdvertisement")
                        .WithMany()
                        .HasForeignKey("ReportedAdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId");

                    b.Navigation("ReportedAdvertisement");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Role", null)
                        .WithMany("IdentityUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.MessageAttachment", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeNameLocaleText", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Attribute", null)
                        .WithMany("AttributeNameLocales")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListEntryLocaleText", b =>
                {
                    b.HasOne("BusinessLogic.Entities.AttributeValueListEntry", "ListEntry")
                        .WithMany("LocalisedNames")
                        .HasForeignKey("AttributeValueListEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListEntry");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListLocaleText", b =>
                {
                    b.HasOne("BusinessLogic.Entities.AttributeValueList", "ValueList")
                        .WithMany("LocalisedNames")
                        .HasForeignKey("AttributeValueListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValueList");
                });

            modelBuilder.Entity("BusinessLogic.Entities.CategoryNameLocaleText", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Category", null)
                        .WithMany("LocalisedNames")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.AdvertisementImage", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Advertisement", "Advertisement")
                        .WithMany("Images")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Files.UserImage", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", "OwnerUser")
                        .WithOne("ProfileImageFile")
                        .HasForeignKey("BusinessLogic.Entities.Files.UserImage", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Advertisement", b =>
                {
                    b.Navigation("AdvertisementBookmarks");

                    b.Navigation("AttributeValues");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AdvertisementNotificationSubscription", b =>
                {
                    b.Navigation("AttributeFilters");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Attribute", b =>
                {
                    b.Navigation("AttributeNameLocales");

                    b.Navigation("CategoryAttributes");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueList", b =>
                {
                    b.Navigation("ListEntries");

                    b.Navigation("LocalisedNames");
                });

            modelBuilder.Entity("BusinessLogic.Entities.AttributeValueListEntry", b =>
                {
                    b.Navigation("LocalisedNames");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Category", b =>
                {
                    b.Navigation("CategoryAttributes");

                    b.Navigation("ChildCategories");

                    b.Navigation("LocalisedNames");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Chat", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatUsers");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Message", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Role", b =>
                {
                    b.Navigation("IdentityUserRoles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BusinessLogic.Entities.User", b =>
                {
                    b.Navigation("AdvertisementBookmarks");

                    b.Navigation("OwnedAdvertisements");

                    b.Navigation("ProfileImageFile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
